/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColumnsRouteImport } from './routes/columns'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ViewRouteImport } from './routes/view'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as ColumnSlugRouteImport } from './routes/column.$slug'
import { Route as TopicTopicIdRouteImport } from './routes/topic.$topicId'
import { Route as ReadBookIdKindChapRouteImport } from './routes/read.$bookId.$kind.$chap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnsRoute = ColumnsRouteImport.update({
  id: '/columns',
  path: '/columns',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRoute = ViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnSlugRoute = ColumnSlugRouteImport.update({
  id: '/column/$slug',
  path: '/column/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdKindChapRoute = ReadBookIdKindChapRouteImport.update({
  id: '/read/$bookId/$kind/$chap',
  path: '/read/$bookId/$kind/$chap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/columns': typeof ColumnsRoute
  '/intro': typeof IntroRoute
  '/people': typeof PeopleRoute
  '/topics': typeof TopicsRoute
  '/view': typeof ViewRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/read/$bookId/$kind/$chap': typeof ReadBookIdKindChapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/columns': typeof ColumnsRoute
  '/intro': typeof IntroRoute
  '/people': typeof PeopleRoute
  '/topics': typeof TopicsRoute
  '/view': typeof ViewRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/read/$bookId/$kind/$chap': typeof ReadBookIdKindChapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/columns': typeof ColumnsRoute
  '/intro': typeof IntroRoute
  '/people': typeof PeopleRoute
  '/topics': typeof TopicsRoute
  '/view': typeof ViewRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/column/$slug': typeof ColumnSlugRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/read/$bookId/$kind/$chap': typeof ReadBookIdKindChapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/columns'
    | '/intro'
    | '/people'
    | '/topics'
    | '/view'
    | '/book/$bookId'
    | '/column/$slug'
    | '/topic/$topicId'
    | '/read/$bookId/$kind/$chap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/columns'
    | '/intro'
    | '/people'
    | '/topics'
    | '/view'
    | '/book/$bookId'
    | '/column/$slug'
    | '/topic/$topicId'
    | '/read/$bookId/$kind/$chap'
  id:
    | '__root__'
    | '/'
    | '/columns'
    | '/intro'
    | '/people'
    | '/topics'
    | '/view'
    | '/book/$bookId'
    | '/column/$slug'
    | '/topic/$topicId'
    | '/read/$bookId/$kind/$chap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColumnsRoute: typeof ColumnsRoute
  IntroRoute: typeof IntroRoute
  PeopleRoute: typeof PeopleRoute
  TopicsRoute: typeof TopicsRoute
  ViewRoute: typeof ViewRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ColumnSlugRoute: typeof ColumnSlugRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
  ReadBookIdKindChapRoute: typeof ReadBookIdKindChapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/columns': {
      id: '/columns'
      path: '/columns'
      fullPath: '/columns'
      preLoaderRoute: typeof ColumnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column/$slug': {
      id: '/column/$slug'
      path: '/column/$slug'
      fullPath: '/column/$slug'
      preLoaderRoute: typeof ColumnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId/$kind/$chap': {
      id: '/read/$bookId/$kind/$chap'
      path: '/read/$bookId/$kind/$chap'
      fullPath: '/read/$bookId/$kind/$chap'
      preLoaderRoute: typeof ReadBookIdKindChapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColumnsRoute: ColumnsRoute,
  IntroRoute: IntroRoute,
  PeopleRoute: PeopleRoute,
  TopicsRoute: TopicsRoute,
  ViewRoute: ViewRoute,
  BookBookIdRoute: BookBookIdRoute,
  ColumnSlugRoute: ColumnSlugRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
  ReadBookIdKindChapRoute: ReadBookIdKindChapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
